# Generated by Django 3.0.5 on 2020-11-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201117_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product_spec'),
        ),
    ]
