# Generated by Django 3.0.5 on 2020-11-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201117_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mode',
            old_name='mode',
            new_name='modes',
        ),
        migrations.RenameField(
            model_name='product_spec',
            old_name='spec',
            new_name='specs',
        ),
    ]
